#  _    _ _   _           _                      _             _  
# | | _(_) |_| |_ _   _  | |_ ___ _ __ _ __ ___ (_)_ __   __ _| | 
# | |/ / | __| __| | | | | __/ _ \ '__| '_ ` _ \| | '_ \ / _` | | 
# |   <| | |_| |_| |_| | | ||  __/ |  | | | | | | | | | | (_| | | 
# |_|\_\_|\__|\__|\__, |  \__\___|_|  |_| |_| |_|_|_| |_|\__,_|_| 
#                 |___/              _          _   _             
#   ___ _   _ ___| |_ ___  _ __ ___ (_)______ _| |_(_) ___  _ __  
#  / __| | | / __| __/ _ \| '_ ` _ \| |_  / _` | __| |/ _ \| '_ \ 
# | (__| |_| \__ \ || (_) | | | | | | |/ / (_| | |_| | (_) | | | |
#  \___|\__,_|___/\__\___/|_| |_| |_|_/___\__,_|\__|_|\___/|_| |_|

##########################################################################

# themes
include GruvBox_DarkHard.conf
# include Wryan.conf
# include VSCode_Dark.conf

# terminal opacity and blur
background_opacity 0.65
background_blur 1

# advance 
term xterm-kitty

# terminal bell
enable_audio_bell no

# os specific tweaks (Gnome window decoration for wayland)
# linux_display_server x11

# font
font_family        FiraCode Nerd Font
# font_family monospace
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size          12.0

# font size management 
map ctrl+shift+backspace change_font_size all 0

# cursor customization
# block / beam / underline
cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval 0.5
cursor_stop_blinking_after 0
shell_integration no-cursor
cursor_trail 1
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 0
# cursor_trail_color #C742FF
# cursor_trail_color #FE8019
# cursor_trail_color #88C0D0
scrollback_lines 5000
scrollbar hovered
wheel_scroll_multiplier 3.0

# mouse
mouse_hide_wait 3

# window layout
remember_window_size yes
initial_window_width 1200
initial_window_height 750
window_border_width 1.5pt
enabled_layouts tall
window_padding_width 0
window_margin_width 1
hide_window_decorations yes

# window management 
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# layout management
map ctrl+shift+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stack

# tab bar customization
tab_bar_style powerline
tab_powerline_style angled
tab_bar_edge bottom
tab_bar_align center
active_tab_font_style   bold
inactive_tab_font_style normal

# Tab bar colors (GruvBox Dark Hard)
active_tab_foreground   #FBF1C7
active_tab_background   #FE8019
inactive_tab_foreground #928374
inactive_tab_background #3C3836

# tab management
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab

# windows close warn
# confirm_os_window_close 0
