source = ~/.config/hypr/conf.d/variables.conf
source = ~/.config/hypr/conf.d/decorations.conf
source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/windowrules.conf
source = ~/.config/hypr/conf.d/keybindings.conf

monitor=,preferred,auto,auto

exec-once = waybar 
exec-once = awww-daemon
exec-once = sleep 2 && otd-daemon & 
exec-once = swaync
exec-once = wl-paste --watch cliphist store -max-items 100
exec-once = nm-applet --indicator

env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

general {
    gaps_in = 4
    gaps_out = 8

    border_size = 2

    col.active_border = rgb(88C0D0) rgb(81A1C1) 45deg
    col.inactive_border = rgb(3B4252)

    layout = dwindle
    resize_on_border = true
}

dwindle {
    preserve_split = true
    force_split = 2
}

misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = true 
}

input {
    kb_layout = us,ru
    kb_options = grp:alt_shift_toggle

    follow_mouse = 1

    sensitivity = 0 

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

$mainMod = SUPER 

