# Палитра Nord (Snow & Frost)
$nord0 = rgb(2E3440) # Background
$nord1 = rgb(3B4252) # Inactive
$nord3 = rgb(4C566A) # Comments
$nord4 = rgb(D8DEE9) # Foreground
$nord8 = rgb(88C0D0) # Frost Cyan
$nord9 = rgb(81A1C1) # Frost Blue
$nord10 = rgb(5E81AC) # Frost Dark Blue

$mainMod = SUPER # Win / Cmd

$terminal = kitty 
$fileManager = thunar & 
$menu = rofi -show drun
$browser = zen-browser
$cliphistcmd = ~/.local/bin/cliphist-launcher.sh
$vpnApp = happ
